project:
  type: website
lang: nl
website:
  title: "Working document AI platform"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Let op** - dit is een werkdocument dat bedoeld is om met experts, partners en andere belanghebbenden in discussie te gaan."
    type: primary
    position: above-navbar
  reader-mode: true
  sidebar:
    search: true
    style: floating
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/company/health-ri/
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/Health-RI/AIDA
        text: "GitHub repository"
    contents:
      - href: index.qmd
        text: Startnotitie
      - section: "Strategisch perspectief"
        href: strategisch/index.qmd
        contents:
          - href: strategisch/aida.qmd
            text: "Verhaallijn AIDA"          
          - href: strategisch/blauwdrukken.qmd
            text: "Vergelijking blauwdrukken"
          - href: strategisch/valleys.qmd
            text: "Achtergrond"          
          # - href: strategisch/plugin.qmd
          #   text: "Voorbeeld: Amsterdam Health Data Space"
          # - href: strategisch/plugin.qmd
          #   text: "Voorbeeld: AnDREa"
          # - href: strategisch/plugin.qmd
          #   text: "Voorbeeld: PLUGIN"
          # - href: strategisch/mpc.qmd
          #   text: "Voorbeeld: Multiparty Computation"
      - section: "Business perspectief"
        href: business/index.qmd
        contents:        
          - business/personas/index.qmd
          - business/verhaallijn-data-engineer.qmd
          - business/verhaallijn-ml-engineer.qmd
      - section: "Applicaties en technisch perspectief"
        href: technisch/index.qmd
        contents:  
          - href: "https://health-ri.github.io/AIDA-Archimate/"
            text: "AIDA Archimate viewer"
            target: _blank
          - href: "https://health-ri.github.io/simple-open-architecture/"
            text: "Simpl Open Archimate viewer"
            target: _blank
  page-navigation: true

format:
  html:
    grid:
      sidebar-width: 280px
    theme:
      - cosmo
      - brand
      - custom.scss
    css: styles.css
    toc: true
  typst:
    brand: /_brand.yml
    lang: nl-nl
    papersize: a4

comments:
  giscus: 
    repo: health-ri/aida
bibliography: health-ri.bib
filters:
  - d2
d2:
  format: svg
  embed_mode: raw
