direction: right
data platform <-> data gateway <-> aida -> output control
aida: {
  direction: right
  workbench <-> storage services
  workbench <-> compute services
  workbench: {
    IDE
    library registry
  }
  storage services: {
    vector database
    blob storage
    block storage
  }
  compute services: {
    centralised processing
    federated processing
  }
}
output control: {
  model exchange standard
  statistical disclosure control
}